### ISSUE TITLE
是否可以编译一个IPQ806x可用的1.2.1集成PDNSD功能的包？

### ISSUE THREAD

**Issue by daniuer** [Feibugs/LEDE-SSR#1]
希望大神出手能编译出这个包，不胜感激。

**Comment by daniuer** [comment]
非常感谢大大，我都准备自己去学编译了。没想到这样快就发布了最新版本，实在是不知道怎么表达感激之情。

**Comment by daniuer** [comment]
不过希望大大不要公开发布IPK包，只分享给几位应求发布的网友，因为我所知有人盗用ywb94大编译好的SSR包，集成到自己商业用的OP固件里，并且修改加上自己的SS商业网站推广自己的SS服务，这是导致ywb94不再做后续开发的原因。不想看到大大费尽心力好心编译的IPK，又被盗用后被人免费做嫁衣。

**Comment by Feibugs** [comment]
确实是这样，大家低调用吧，本来天朝上网就不容易，大家能互相帮忙就帮一下。

我这个github目录也是做个备份而已，代码和ywb94的完全一样

**Comment by daniuer** [comment]
好的，非常感谢，再次表示由衷的感激！
